### PR TITLE
Err display

### LINKED ISSUE #157: Centralized error logging
Current the library outputs certain errors to the terminal by following a particular string formats:
- `"error_message"`
- `"*-*-* #{error_msg}"`
- `%|*-*-* #{e.class}: #{e.message}\n#{e.backtrace.join("\n  ")}|`
- `%|*-*-* #{e.class}: #{e.message}\n      #{e.backtrace.join("\n      ")}|`

It'd be better if the format was standardized and centrally defined so that:
  - consistency :slightly_smiling_face:
  - contributors need not think about formatting the error message

### PR DESCRIPTION
**Pull request by ohler55**
Fixes #157 
Normalizes error displays.

### CODE REVIEW

File: lib/wab/impl/handler.rb [hunk 1]
```diff
@@ -87,13 +87,10 @@ def send_result(result, res, path, query)
...
-        error_class = e.class
-        error_msg = e.message
-        backtrace = e.backtrace
-        body = { code: -1, error: "#{error_class}: #{error_msg}" }
-        body[:backtrace] = backtrace
+        body = { code: -1, error: "#{e.class}: #{e.message}" }
+        body[:backtrace] = e.backtrace
         res.body = @shell.data(body).json(@shell.indent)
-        @shell.logger.warn(%|*-*-* #{error_class}: #{error_msg}\n      #{backtrace.join("\n      ")}|)
+        @shell.logger.warn(format_error(e))
```
Comment (ashmaroli) [inline lib/wab/impl/handler.rb]:
```ruby
Impl.format_error(e)
```
